name: Deploy to github pages
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Dependency Installation
        run: yarn install --frozen-lockfile

      - name: Building
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: pages
          folder: build
