name: Build Tests

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Dependency Installation
        run: yarn install --frozen-lockfile

      - name: Linting & Testing
        run: |
          yarn lint
          yarn tsc
